In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [27]:
exchange_rates_df = pd.read_csv("data/USD_INRHistoricalData.csv")
exchange_rates_df = exchange_rates_df[['Date', 'Open', 'High', 'Low', 'Price']]
for column in exchange_rates_df:
    exchange_rates_df[column] = exchange_rates_df[column][::-1].values
print (exchange_rates_df.head)

<bound method NDFrame.head of               Date    Open    High     Low   Price
0     Jan 01, 2010  46.610  46.677  46.590  46.615
1     Jan 04, 2010  46.545  46.655  46.245  46.295
2     Jan 05, 2010  46.305  46.305  46.045  46.205
3     Jan 06, 2010  46.165  46.205  45.695  45.695
4     Jan 07, 2010  45.610  45.890  45.570  45.650
5     Jan 08, 2010  45.680  45.900  45.470  45.470
6     Jan 11, 2010  45.510  45.510  45.230  45.260
7     Jan 12, 2010  45.140  45.750  45.100  45.660
8     Jan 13, 2010  45.735  45.775  45.415  45.495
9     Jan 14, 2010  45.490  45.720  45.400  45.600
10    Jan 15, 2010  45.620  45.830  45.410  45.790
11    Jan 18, 2010  45.785  45.855  45.515  45.645
12    Jan 19, 2010  45.660  45.900  45.360  45.760
13    Jan 20, 2010  45.800  46.130  45.540  45.860
14    Jan 21, 2010  45.780  46.230  45.720  46.230
15    Jan 22, 2010  46.305  46.355  46.025  46.225
16    Jan 25, 2010  46.175  46.275  46.025  46.075
17    Jan 26, 2010  45.995  45.995  45.855  45.855
18    Jan 27, 2010  45.870  46.540  45.870  46.190
19    Jan 28, 2010  46.380  46.470  46.150  46.250
20    Jan 29, 2010  46.275  46.445  46.075  46.125
21    Feb 01, 2010  46.160  46.450  46.030  46.140
22    Feb 02, 2010  46.075  46.335  45.955  46.125
23    Feb 03, 2010  46.045  46.155  45.925  45.925
24    Feb 04, 2010  45.995  46.285  45.785  46.235
25    Feb 05, 2010  46.275  46.775  46.075  46.645
26    Feb 08, 2010  46.555  46.890  46.395  46.845
27    Feb 09, 2010  46.765  46.815  46.385  46.405
28    Feb 10, 2010  46.315  46.685  46.205  46.365
29    Feb 11, 2010  46.355  46.525  46.325  46.355
...            ...     ...     ...     ...     ...
2305  Aug 26, 2018  69.775  69.775  69.775  69.775
2306  Aug 27, 2018  69.765  70.165  69.705  70.165
2307  Aug 28, 2018  70.050  70.297  70.050  70.100
2308  Aug 29, 2018  70.325  70.635  70.240  70.535
2309  Aug 30, 2018  70.635  70.875  70.595  70.745
2310  Aug 31, 2018  70.955  71.025  70.855  71.005
2311  Sep 02, 2018  71.005  71.005  71.005  71.005
2312  Sep 03, 2018  70.790  71.220  70.725  71.215
2313  Sep 04, 2018  71.285  71.585  71.095  71.585
2314  Sep 05, 2018  71.405  71.955  71.375  71.755
2315  Sep 06, 2018  71.630  72.105  71.630  71.950
2316  Sep 07, 2018  71.960  72.045  71.665  71.790
2317  Sep 09, 2018  72.105  72.105  72.105  72.105
2318  Sep 10, 2018  72.135  72.680  72.075  72.455
2319  Sep 11, 2018  72.310  72.750  72.250  72.640
2320  Sep 12, 2018  72.843  72.920  71.925  72.160
2321  Sep 13, 2018  72.037  72.037  72.037  72.037
2322  Sep 14, 2018  71.700  71.995  71.535  71.880
2323  Sep 16, 2018  72.105  72.105  72.105  72.105
2324  Sep 17, 2018  72.530  72.695  72.315  72.540
2325  Sep 18, 2018  72.560  72.990  72.360  72.710
2326  Sep 19, 2018  72.720  72.875  72.345  72.360
2327  Sep 20, 2018  72.345  72.345  72.015  72.015
2328  Sep 21, 2018  71.860  72.480  71.760  72.240
2329  Sep 23, 2018  72.240  72.240  72.240  72.240
2330  Sep 24, 2018  72.480  72.740  72.340  72.670
2331  Sep 25, 2018  72.905  72.960  72.575  72.685
2332  Sep 26, 2018  72.710  72.755  72.537  72.600
2333  Sep 27, 2018  72.430  72.770  72.390  72.570
2334  Sep 28, 2018  72.570  72.670  72.405  72.510

[2335 rows x 5 columns]>